networks:
    postmanagement_network:
        driver: bridge

services:
  post_management.ui:
    container_name: postmanagement-ui
    build:
      context: ./Post_Management.UI
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # External port 8080, internal nginx port 80
    depends_on:
      - post_management.api
    networks:
      - postmanagement_network
    restart: unless-stopped

  post_management.api:
    container_name: postmanagement-api
    image: ${DOCKER_REGISTRY-}postmanagementapi
    build:
      context: .
      dockerfile: Post_Management.API/Dockerfile
    ports:
      - "5000:5000"  # External port 5000, internal port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__PostgresConnection=Host=192.168.0.114;Database=PostManagementDB;Username=casaos;Password=casaos;Port=5432
      - EXTERNAL_API_HOST=localhost
    networks:
      - postmanagement_network
    volumes:
      - post_management.images:/app/Images
    restart: unless-stopped

volumes:
  post_management.images: